# STATUS: FAIL!!
FROM ubuntu:18.04
RUN apt-get update && \
    apt-get install -y build-essential manpages-dev vim git-core \
                       libsuitesparse-dev gcc libc6-dev gfortran libgfortran3 python3 python3-dev python3-pip python3-setuptools
RUN pip3 install --upgrade pip && \
    pip3 install --upgrade numpy matplotlib && \
    pip3 install --upgrade scikit-sparse
WORKDIR /home
RUN git clone https://bitbucket.org/dabi86/transportmaps.git
WORKDIR /home/transportmaps
RUN pip3 install --upgrade -r requirements.txt
RUN python setup.py install
WORKDIR /home
