version: '3'
services:
  nodejs:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: tianxiang84/nodejs
    container_name: nodejs
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../app_test/:/home/TSu/app_test
    env_file:
      javascript.env
    working_dir: /home/TSu/app_test
